In [20]:
import pandas as pd

# Merge the railroad data

In [21]:
data1 = pd.read_csv('Railroads Data\Railroad Retirement Payments by State.csv')
data2 = pd.read_csv('Railroads Data\Freight Rail Average Wages & Benefits Per Employee.csv')
data3 = pd.read_csv('Railroads Data\Freight Rail Employment.csv')
data4 = pd.read_csv('Railroads Data\Freight Railroads by State.csv')
data5 = pd.read_csv('Railroads Data\Originated Rail Carloads by State.csv')
data6 = pd.read_csv('Railroads Data\Originated Rail Tons by State.csv')
data7 = pd.read_csv('Railroads Data\Railroad Retirement Beneficiaries by State.csv')
data8 = pd.read_csv('Railroads Data\Terminated Rail Carloads by State.csv')
data9 = pd.read_csv('Railroads Data\Terminated Rail Tons by State.csv')
data10 = pd.read_csv('Railroads Data\Total Rail Miles by State.csv')

output1 = pd.merge(data1, data2[['State', 'Freight Rail Average Wages & Benefits Per Employee']],
				on='State',
				how='left')

output2 = pd.merge(output1, data3[['State', 'Freight Rail Employees']],
				on='State',
				how='left')

output3 = pd.merge(output2, data4[['State', 'Number of Railroads']],
				on='State',
				how='left')

output4 = pd.merge(output3, data5[['State', 'Originated Carloads']],
				on='State',
				how='left')

output5 = pd.merge(output4, data6[['State', 'Originated Tons (millions)']],
				on='State',
				how='left')

output6 = pd.merge(output5, data7[['State', 'Retirement Beneficiaries']],
				on='State',
				how='left')

output7 = pd.merge(output6, data8[['State', 'Terminated Carloads']],
				on='State',
				how='left')

output8 = pd.merge(output7, data9[['State', 'Terminated Tons (millions)']],
				on='State',
				how='left')

output9 = pd.merge(output8, data10[['State', 'Total Rail Miles']],
				on='State',
				how='left')

print(output3)

    Rank                 State Retirement Payments ($ mil)  \
0      1                 Texas                        $956
1      2              Illinois                        $808
2      3               Florida                        $759
3      4          Pennsylvania                        $745
4      5            California                        $610
5      6              New York                        $543
6      7                  Ohio                        $537
7      8              Missouri                        $487
8      9              Nebraska                        $453
9     10               Georgia                        $451
10    11              Virginia                        $395
11    12               Indiana                        $390
12    13                Kansas                        $356
13    14              Kentucky                        $339
14    15             Minnesota                        $331
15    16             Tennessee                        $309
16    17              Michigan                        $306
17    18            Washington                        $268
18    19               Arizona                        $257
19    20              Arkansas                        $257
20    21            New Jersey                        $246
21    22        North Carolina                        $241
22    23               Alabama                        $240
23    24              Colorado                        $233
24    25             Wisconsin                        $233
25    26                  Iowa                        $232
26    27              Maryland                        $214
27    28         West Virginia                        $190
28    29             Louisiana                        $189
29    30                Oregon                        $184
30    31        South Carolina                        $183
31    32               Montana                        $166
32    33           Mississippi                        $137
33    34                  Utah                        $130
34    35              Oklahoma                        $123
35    36                 Idaho                        $122
36    37               Wyoming                        $116
37    38            New Mexico                        $102
38    39         Massachusetts                         $99
39    40          North Dakota                         $87
40    41                Nevada                         $80
41    42           Connecticut                         $77
42    43              Delaware                         $72
43    44                 Maine                         $50
44    45          South Dakota                         $50
45    46         New Hampshire                         $23
46    47          Rhode Island                         $16
47    48               Vermont                         $14
48    49  District of Columbia                          $8
49    50                Alaska                          $4
50    51                Hawaii                          $4

   Freight Rail Average Wages & Benefits Per Employee Freight Rail Employees  \
0                                            $146,200                 14,664
1                                            $134,500                  9,902
2                                            $150,300                  3,577
3                                            $120,830                  4,528
4                                            $136,840                  6,936
5                                            $127,510                  2,389
6                                            $128,510                  5,036
7                                            $133,750                  5,740
8                                            $138,960                  8,436
9                                            $143,050                  5,428
10                                           $141,490                  2,738
11                                           $132,790                  4,798
12                                           $134,030                  4,296
13                                           $128,850                  2,457
14                                           $132,590                  3,750
15                                           $133,000                  2,816
16                                           $125,080                  2,352
17                                           $138,420                  3,619
18                                           $143,050                  2,389
19                                           $123,690                  2,276
20                                           $119,780                    887
21                                           $132,430                  1,614
22                                           $131,300                  2,561
23                                           $137,320                  1,814
24                                           $135,890                  2,732
25                                           $134,580                  2,658
26                                           $128,920                    737
27                                           $125,870                  1,495
28                                           $127,630                  2,600
29                                           $122,140                  1,337
30                                           $136,500                  1,237
31                                           $131,230                  2,772
32                                           $133,200                  1,733
33                                           $131,520                  1,150
34                                           $126,220                  1,766
35                                           $126,290                  1,176
36                                           $136,770                  1,609
37                                           $138,850                  1,349
38                                           $111,830                    593
39                                           $139,470                  1,458
40                                           $141,660                    514
41                                           $107,060                    111
42                                           $119,090                    147
43                                           $110,070                    466
44                                           $129,640                    665
45                                           $112,280                    169
46                                           $118,270                     28
47                                            $86,750                    185
48                                                NaN                     10
49                                           $105,420                    609
50                                                NaN                      5

    Number of Railroads
0                  54.0
1                  47.0
2                  16.0
3                  59.0
4                  27.0
5                  38.0
6                  43.0
7                  17.0
8                  10.0
9                  29.0
10                 10.0
11                 43.0
12                 14.0
13                 15.0
14                 19.0
15                 27.0
16                 28.0
17                 29.0
18                 10.0
19                 24.0
20                 19.0
21                 22.0
22                 25.0
23                 14.0
24                  9.0
25                 17.0
26                  9.0
27                 11.0
28                 21.0
29                 22.0
30                 11.0
31                  7.0
32                 27.0
33                  8.0
34                 18.0
35                 10.0
36                  6.0
37                  6.0
38                 13.0
39                  7.0
40                  2.0
41                  8.0
42                  6.0
43                  7.0
44                 11.0
45                 10.0
46                  1.0
47                 10.0
48                  NaN
49                  1.0
50                  0.0

In [22]:
output9.to_csv('data_merge.csv', index = False)  # Export merged pandas DataFrame

In [23]:
merged_data = pd.read_csv('data_merge.csv')
merged_data

,Rank,State,Retirement Payments ($ mil),Freight Rail Average Wages & Benefits Per Employee,Freight Rail Employees,Number of Railroads,Originated Carloads,Originated Tons (millions),Retirement Beneficiaries,Terminated Carloads,Terminated Tons (millions),Total Rail Miles
0,1,Texas,$956,"$146,200","14,664",54.0,"2,161,300",110.9,"33,300","2,875,900",181.9,"10,370"
1,2,Illinois,$808,"$134,500","9,902",47.0,"4,002,900",118.9,"29,600","3,839,700",101.4,"6,768"
2,3,Florida,$759,"$150,300","3,577",16.0,"639,400",39.5,"28,700","990,400",57.2,"2,716"
3,4,Pennsylvania,$745,"$120,830","4,528",59.0,"960,200",50,"28,600","1,074,900",49.5,"5,228"
4,5,California,$610,"$136,840","6,936",27.0,"3,414,100",63.8,"23,900","3,684,400",100.8,"4,948"
5,6,New York,$543,"$127,510","2,389",38.0,"192,600",9.7,"20,300","295,100",15.7,"3,442"
6,7,Ohio,$537,"$128,510","5,036",43.0,"1,081,600",52.8,"21,000","1,069,200",60.9,"5,139"
7,8,Missouri,$487,"$133,750","5,740",17.0,"451,000",22,"17,700","654,000",50.0,"3,734"
8,9,Nebraska,$453,"$138,960","8,436",10.0,"377,800",34.5,"14,500","216,600",19.4,"3,138"
9,10,Georgia,$451,"$143,050","5,428",29.0,"1,138,900",38.4,"16,400","1,308,400",54.1,"4,538"
10,11,Virginia,$395,"$141,490","2,738",10.0,"538,900",26.9,"15,000","871,600",56.1,"3,050"
11,12,Indiana,$390,"$132,790","4,798",43.0,"632,400",50.2,"14,300","594,800",53.2,"3,946"
12,13,Kansas,$356,"$134,030","4,296",14.0,"458,600",28.6,"12,500","368,500",18.2,"4,748"
13,14,Kentucky,$339,"$128,850","2,457",15.0,"366,400",22.6,"13,200","269,400",19.4,"2,673"
14,15,Minnesota,$331,"$132,590","3,750",19.0,"1,186,900",99.1,"12,600","954,300",75.1,"4,373"
15,16,Tennessee,$309,"$133,000","2,816",27.0,"531,300",14.7,"11,500","636,000",25.0,"2,730"
16,17,Michigan,$306,"$125,080","2,352",28.0,"525,700",20.9,"11,500","502,800",28.7,"3,429"
17,18,Washington,$268,"$138,420","3,619",29.0,"792,100",20.2,"9,700","1,215,800",68.2,"2,867"
18,19,Arizona,$257,"$143,050","2,389",10.0,"133,900",4.3,"9,600","301,000",19.5,"1,724"
19,20,Arkansas,$257,"$123,690","2,276",24.0,"296,800",16.4,"9,400","319,400",22.4,"2,554"
20,21,New Jersey,$246,"$119,780",887,19.0,"714,800",15.7,"8,500","766,200",22.6,"1,087"
21,22,North Carolina,$241,"$132,430","1,614",22.0,"295,600",12.7,"9,700","546,500",37.5,"3,125"
22,23,Alabama,$240,"$131,300","2,561",25.0,"416,400",32.6,"8,900","430,000",38.0,"3,165"
23,24,Colorado,$233,"$137,320","1,814",14.0,"264,100",15.2,"8,300","397,600",27.0,"2,545"
24,25,Wisconsin,$233,"$135,890","2,732",9.0,"252,900",22.9,"8,900","416,600",39.2,"3,482"
25,26,Iowa,$232,"$134,580","2,658",17.0,"517,100",48.3,"8,500","257,300",24.5,"3,827"
26,27,Maryland,$214,"$128,920",737,9.0,"77,800",3.9,"8,100","342,900",29.8,722
27,28,West Virginia,$190,"$125,870","1,495",11.0,"468,100",52.6,"7,000","77,300",7.6,"2,123"
28,29,Louisiana,$189,"$127,630","2,600",21.0,"444,200",37.2,"6,900","423,300",37.0,"3,001"
29,30,Oregon,$184,"$122,140","1,337",22.0,"302,200",11.3,"7,000","423,600",17.2,"2,369"
30,31,South Carolina,$183,"$136,500","1,237",11.0,"355,000",14,"7,000","527,300",27.1,"2,191"
31,32,Montana,$166,"$131,230","2,772",7.0,"302,700",32.1,"5,700","44,500",3.5,"3,680"
32,33,Mississippi,$137,"$133,200","1,733",27.0,"121,200",9,"5,200","144,400",13.1,"2,541"
33,34,Utah,$130,"$131,520","1,150",8.0,"258,500",15.7,"4,600","241,300",11.6,"1,388"
34,35,Oklahoma,$123,"$126,220","1,766",18.0,"211,900",19.3,"4,600","186,500",17.6,"3,222"
35,36,Idaho,$122,"$126,290","1,176",10.0,"92,700",8.7,"4,300","102,700",9.7,"1,654"
36,37,Wyoming,$116,"$136,770","1,609",6.0,"2,020,000",230.4,"3,600","99,800",10.1,"1,860"
37,38,New Mexico,$102,"$138,850","1,349",6.0,"121,200",6.2,"3,800","107,400",5.2,"1,859"
38,39,Massachusetts,$99,"$111,830",593,13.0,"130,400",4.3,"3,600","222,700",8.3,868
39,40,North Dakota,$87,"$139,470","1,458",7.0,"375,500",35.7,"2,900","127,900",12.3,"3,223"
40,41,Nevada,$80,"$141,660",514,2.0,"38,500",2.5,"3,100","79,300",5.4,"1,193"
41,42,Connecticut,$77,"$107,060",111,8.0,"14,400",1.4,"2,600","15,100",1.4,571
42,43,Delaware,$72,"$119,090",147,6.0,"4,700",0.4,"2,500","40,000",3.0,230
43,44,Maine,$50,"$110,070",466,7.0,"23,400",1.8,"2,100","22,500",1.9,"1,116"
44,45,South Dakota,$50,"$129,640",665,11.0,"167,700",16.4,"1,700","35,400",3.4,"1,868"
45,46,New Hampshire,$23,"$112,280",169,10.0,"1,430",0.1,900,"7,300",0.6,369
46,47,Rhode Island,$16,"$118,270",28,1.0,500,(a),600,"6,500",0.5,143
47,48,Vermont,$14,"$86,750",185,10.0,"6,800",0.6,600,"12,400",1.0,607
48,49,District of Columbia,$8,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Alaska,$4,"$105,420",609,1.0,NaN,2.5,200,NaN,2.5,506
50,51,Hawaii,$4,NaN,5,0.0,0,0,200,NaN,0.0,0

# Fix the railraod data

In [24]:
# convert rows into float and remove $ and commas : Retirement Payments ($ mil), Freight Rail Average Wages & Benefits Per Employee 
merged_data['Retirement Payments ($ mil)'] = merged_data['Retirement Payments ($ mil)'].replace({'\$': '', ',': ''}, regex=True).astype(float)
merged_data['Freight Rail Average Wages & Benefits Per Employee'] = merged_data['Freight Rail Average Wages & Benefits Per Employee']\
                                                .replace({'\$': '', ',': ''}, regex=True).astype(float)

# convert rows into floats and remove commas: Freight Rail Employees, Originated Carloads, Retirement Beneficiaries, Terminated Carloads, Total Rail Miles

merged_data['Freight Rail Employees'] = merged_data['Freight Rail Employees'].replace({',': ''}, regex=True).astype(float)
merged_data['Originated Carloads'] = merged_data['Originated Carloads'].replace({',': ''}, regex=True).astype(float)
merged_data['Retirement Beneficiaries'] = merged_data['Retirement Beneficiaries'].replace({',': ''}, regex=True).astype(float)
merged_data['Terminated Carloads'] = merged_data['Terminated Carloads'].replace({',': ''}, regex=True).astype(float)
merged_data['Total Rail Miles'] = merged_data['Total Rail Miles'].replace({',': ''}, regex=True).astype(float)

merged_data

,Rank,State,Retirement Payments ($ mil),Freight Rail Average Wages & Benefits Per Employee,Freight Rail Employees,Number of Railroads,Originated Carloads,Originated Tons (millions),Retirement Beneficiaries,Terminated Carloads,Terminated Tons (millions),Total Rail Miles
0,1,Texas,956.0,146200.0,14664.0,54.0,2161300.0,110.9,33300.0,2875900.0,181.9,10370.0
1,2,Illinois,808.0,134500.0,9902.0,47.0,4002900.0,118.9,29600.0,3839700.0,101.4,6768.0
2,3,Florida,759.0,150300.0,3577.0,16.0,639400.0,39.5,28700.0,990400.0,57.2,2716.0
3,4,Pennsylvania,745.0,120830.0,4528.0,59.0,960200.0,50,28600.0,1074900.0,49.5,5228.0
4,5,California,610.0,136840.0,6936.0,27.0,3414100.0,63.8,23900.0,3684400.0,100.8,4948.0
5,6,New York,543.0,127510.0,2389.0,38.0,192600.0,9.7,20300.0,295100.0,15.7,3442.0
6,7,Ohio,537.0,128510.0,5036.0,43.0,1081600.0,52.8,21000.0,1069200.0,60.9,5139.0
7,8,Missouri,487.0,133750.0,5740.0,17.0,451000.0,22,17700.0,654000.0,50.0,3734.0
8,9,Nebraska,453.0,138960.0,8436.0,10.0,377800.0,34.5,14500.0,216600.0,19.4,3138.0
9,10,Georgia,451.0,143050.0,5428.0,29.0,1138900.0,38.4,16400.0,1308400.0,54.1,4538.0
10,11,Virginia,395.0,141490.0,2738.0,10.0,538900.0,26.9,15000.0,871600.0,56.1,3050.0
11,12,Indiana,390.0,132790.0,4798.0,43.0,632400.0,50.2,14300.0,594800.0,53.2,3946.0
12,13,Kansas,356.0,134030.0,4296.0,14.0,458600.0,28.6,12500.0,368500.0,18.2,4748.0
13,14,Kentucky,339.0,128850.0,2457.0,15.0,366400.0,22.6,13200.0,269400.0,19.4,2673.0
14,15,Minnesota,331.0,132590.0,3750.0,19.0,1186900.0,99.1,12600.0,954300.0,75.1,4373.0
15,16,Tennessee,309.0,133000.0,2816.0,27.0,531300.0,14.7,11500.0,636000.0,25.0,2730.0
16,17,Michigan,306.0,125080.0,2352.0,28.0,525700.0,20.9,11500.0,502800.0,28.7,3429.0
17,18,Washington,268.0,138420.0,3619.0,29.0,792100.0,20.2,9700.0,1215800.0,68.2,2867.0
18,19,Arizona,257.0,143050.0,2389.0,10.0,133900.0,4.3,9600.0,301000.0,19.5,1724.0
19,20,Arkansas,257.0,123690.0,2276.0,24.0,296800.0,16.4,9400.0,319400.0,22.4,2554.0
20,21,New Jersey,246.0,119780.0,887.0,19.0,714800.0,15.7,8500.0,766200.0,22.6,1087.0
21,22,North Carolina,241.0,132430.0,1614.0,22.0,295600.0,12.7,9700.0,546500.0,37.5,3125.0
22,23,Alabama,240.0,131300.0,2561.0,25.0,416400.0,32.6,8900.0,430000.0,38.0,3165.0
23,24,Colorado,233.0,137320.0,1814.0,14.0,264100.0,15.2,8300.0,397600.0,27.0,2545.0
24,25,Wisconsin,233.0,135890.0,2732.0,9.0,252900.0,22.9,8900.0,416600.0,39.2,3482.0
25,26,Iowa,232.0,134580.0,2658.0,17.0,517100.0,48.3,8500.0,257300.0,24.5,3827.0
26,27,Maryland,214.0,128920.0,737.0,9.0,77800.0,3.9,8100.0,342900.0,29.8,722.0
27,28,West Virginia,190.0,125870.0,1495.0,11.0,468100.0,52.6,7000.0,77300.0,7.6,2123.0
28,29,Louisiana,189.0,127630.0,2600.0,21.0,444200.0,37.2,6900.0,423300.0,37.0,3001.0
29,30,Oregon,184.0,122140.0,1337.0,22.0,302200.0,11.3,7000.0,423600.0,17.2,2369.0
30,31,South Carolina,183.0,136500.0,1237.0,11.0,355000.0,14,7000.0,527300.0,27.1,2191.0
31,32,Montana,166.0,131230.0,2772.0,7.0,302700.0,32.1,5700.0,44500.0,3.5,3680.0
32,33,Mississippi,137.0,133200.0,1733.0,27.0,121200.0,9,5200.0,144400.0,13.1,2541.0
33,34,Utah,130.0,131520.0,1150.0,8.0,258500.0,15.7,4600.0,241300.0,11.6,1388.0
34,35,Oklahoma,123.0,126220.0,1766.0,18.0,211900.0,19.3,4600.0,186500.0,17.6,3222.0
35,36,Idaho,122.0,126290.0,1176.0,10.0,92700.0,8.7,4300.0,102700.0,9.7,1654.0
36,37,Wyoming,116.0,136770.0,1609.0,6.0,2020000.0,230.4,3600.0,99800.0,10.1,1860.0
37,38,New Mexico,102.0,138850.0,1349.0,6.0,121200.0,6.2,3800.0,107400.0,5.2,1859.0
38,39,Massachusetts,99.0,111830.0,593.0,13.0,130400.0,4.3,3600.0,222700.0,8.3,868.0
39,40,North Dakota,87.0,139470.0,1458.0,7.0,375500.0,35.7,2900.0,127900.0,12.3,3223.0
40,41,Nevada,80.0,141660.0,514.0,2.0,38500.0,2.5,3100.0,79300.0,5.4,1193.0
41,42,Connecticut,77.0,107060.0,111.0,8.0,14400.0,1.4,2600.0,15100.0,1.4,571.0
42,43,Delaware,72.0,119090.0,147.0,6.0,4700.0,0.4,2500.0,40000.0,3.0,230.0
43,44,Maine,50.0,110070.0,466.0,7.0,23400.0,1.8,2100.0,22500.0,1.9,1116.0
44,45,South Dakota,50.0,129640.0,665.0,11.0,167700.0,16.4,1700.0,35400.0,3.4,1868.0
45,46,New Hampshire,23.0,112280.0,169.0,10.0,1430.0,0.1,900.0,7300.0,0.6,369.0
46,47,Rhode Island,16.0,118270.0,28.0,1.0,500.0,(a),600.0,6500.0,0.5,143.0
47,48,Vermont,14.0,86750.0,185.0,10.0,6800.0,0.6,600.0,12400.0,1.0,607.0
48,49,District of Columbia,8.0,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Alaska,4.0,105420.0,609.0,1.0,NaN,2.5,200.0,NaN,2.5,506.0
50,51,Hawaii,4.0,NaN,5.0,0.0,0.0,0,200.0,NaN,0.0,0.0

In [25]:
# remove District of Columbia since it only has 2 values and the rest is NaN
merged_data = merged_data[merged_data['State'] != 'District of Columbia']

merged_data

,Rank,State,Retirement Payments ($ mil),Freight Rail Average Wages & Benefits Per Employee,Freight Rail Employees,Number of Railroads,Originated Carloads,Originated Tons (millions),Retirement Beneficiaries,Terminated Carloads,Terminated Tons (millions),Total Rail Miles
0,1,Texas,956.0,146200.0,14664.0,54.0,2161300.0,110.9,33300.0,2875900.0,181.9,10370.0
1,2,Illinois,808.0,134500.0,9902.0,47.0,4002900.0,118.9,29600.0,3839700.0,101.4,6768.0
2,3,Florida,759.0,150300.0,3577.0,16.0,639400.0,39.5,28700.0,990400.0,57.2,2716.0
3,4,Pennsylvania,745.0,120830.0,4528.0,59.0,960200.0,50,28600.0,1074900.0,49.5,5228.0
4,5,California,610.0,136840.0,6936.0,27.0,3414100.0,63.8,23900.0,3684400.0,100.8,4948.0
5,6,New York,543.0,127510.0,2389.0,38.0,192600.0,9.7,20300.0,295100.0,15.7,3442.0
6,7,Ohio,537.0,128510.0,5036.0,43.0,1081600.0,52.8,21000.0,1069200.0,60.9,5139.0
7,8,Missouri,487.0,133750.0,5740.0,17.0,451000.0,22,17700.0,654000.0,50.0,3734.0
8,9,Nebraska,453.0,138960.0,8436.0,10.0,377800.0,34.5,14500.0,216600.0,19.4,3138.0
9,10,Georgia,451.0,143050.0,5428.0,29.0,1138900.0,38.4,16400.0,1308400.0,54.1,4538.0
10,11,Virginia,395.0,141490.0,2738.0,10.0,538900.0,26.9,15000.0,871600.0,56.1,3050.0
11,12,Indiana,390.0,132790.0,4798.0,43.0,632400.0,50.2,14300.0,594800.0,53.2,3946.0
12,13,Kansas,356.0,134030.0,4296.0,14.0,458600.0,28.6,12500.0,368500.0,18.2,4748.0
13,14,Kentucky,339.0,128850.0,2457.0,15.0,366400.0,22.6,13200.0,269400.0,19.4,2673.0
14,15,Minnesota,331.0,132590.0,3750.0,19.0,1186900.0,99.1,12600.0,954300.0,75.1,4373.0
15,16,Tennessee,309.0,133000.0,2816.0,27.0,531300.0,14.7,11500.0,636000.0,25.0,2730.0
16,17,Michigan,306.0,125080.0,2352.0,28.0,525700.0,20.9,11500.0,502800.0,28.7,3429.0
17,18,Washington,268.0,138420.0,3619.0,29.0,792100.0,20.2,9700.0,1215800.0,68.2,2867.0
18,19,Arizona,257.0,143050.0,2389.0,10.0,133900.0,4.3,9600.0,301000.0,19.5,1724.0
19,20,Arkansas,257.0,123690.0,2276.0,24.0,296800.0,16.4,9400.0,319400.0,22.4,2554.0
20,21,New Jersey,246.0,119780.0,887.0,19.0,714800.0,15.7,8500.0,766200.0,22.6,1087.0
21,22,North Carolina,241.0,132430.0,1614.0,22.0,295600.0,12.7,9700.0,546500.0,37.5,3125.0
22,23,Alabama,240.0,131300.0,2561.0,25.0,416400.0,32.6,8900.0,430000.0,38.0,3165.0
23,24,Colorado,233.0,137320.0,1814.0,14.0,264100.0,15.2,8300.0,397600.0,27.0,2545.0
24,25,Wisconsin,233.0,135890.0,2732.0,9.0,252900.0,22.9,8900.0,416600.0,39.2,3482.0
25,26,Iowa,232.0,134580.0,2658.0,17.0,517100.0,48.3,8500.0,257300.0,24.5,3827.0
26,27,Maryland,214.0,128920.0,737.0,9.0,77800.0,3.9,8100.0,342900.0,29.8,722.0
27,28,West Virginia,190.0,125870.0,1495.0,11.0,468100.0,52.6,7000.0,77300.0,7.6,2123.0
28,29,Louisiana,189.0,127630.0,2600.0,21.0,444200.0,37.2,6900.0,423300.0,37.0,3001.0
29,30,Oregon,184.0,122140.0,1337.0,22.0,302200.0,11.3,7000.0,423600.0,17.2,2369.0
30,31,South Carolina,183.0,136500.0,1237.0,11.0,355000.0,14,7000.0,527300.0,27.1,2191.0
31,32,Montana,166.0,131230.0,2772.0,7.0,302700.0,32.1,5700.0,44500.0,3.5,3680.0
32,33,Mississippi,137.0,133200.0,1733.0,27.0,121200.0,9,5200.0,144400.0,13.1,2541.0
33,34,Utah,130.0,131520.0,1150.0,8.0,258500.0,15.7,4600.0,241300.0,11.6,1388.0
34,35,Oklahoma,123.0,126220.0,1766.0,18.0,211900.0,19.3,4600.0,186500.0,17.6,3222.0
35,36,Idaho,122.0,126290.0,1176.0,10.0,92700.0,8.7,4300.0,102700.0,9.7,1654.0
36,37,Wyoming,116.0,136770.0,1609.0,6.0,2020000.0,230.4,3600.0,99800.0,10.1,1860.0
37,38,New Mexico,102.0,138850.0,1349.0,6.0,121200.0,6.2,3800.0,107400.0,5.2,1859.0
38,39,Massachusetts,99.0,111830.0,593.0,13.0,130400.0,4.3,3600.0,222700.0,8.3,868.0
39,40,North Dakota,87.0,139470.0,1458.0,7.0,375500.0,35.7,2900.0,127900.0,12.3,3223.0
40,41,Nevada,80.0,141660.0,514.0,2.0,38500.0,2.5,3100.0,79300.0,5.4,1193.0
41,42,Connecticut,77.0,107060.0,111.0,8.0,14400.0,1.4,2600.0,15100.0,1.4,571.0
42,43,Delaware,72.0,119090.0,147.0,6.0,4700.0,0.4,2500.0,40000.0,3.0,230.0
43,44,Maine,50.0,110070.0,466.0,7.0,23400.0,1.8,2100.0,22500.0,1.9,1116.0
44,45,South Dakota,50.0,129640.0,665.0,11.0,167700.0,16.4,1700.0,35400.0,3.4,1868.0
45,46,New Hampshire,23.0,112280.0,169.0,10.0,1430.0,0.1,900.0,7300.0,0.6,369.0
46,47,Rhode Island,16.0,118270.0,28.0,1.0,500.0,(a),600.0,6500.0,0.5,143.0
47,48,Vermont,14.0,86750.0,185.0,10.0,6800.0,0.6,600.0,12400.0,1.0,607.0
49,50,Alaska,4.0,105420.0,609.0,1.0,NaN,2.5,200.0,NaN,2.5,506.0
50,51,Hawaii,4.0,NaN,5.0,0.0,0.0,0,200.0,NaN,0.0,0.0

In [26]:
# Originated Tons (millions) value (a) converted to < 50000 (0.05 million)
merged_data.loc[merged_data['Originated Tons (millions)'] == '(a)', 'Originated Tons (millions)'] = '<0.05'

merged_data

,Rank,State,Retirement Payments ($ mil),Freight Rail Average Wages & Benefits Per Employee,Freight Rail Employees,Number of Railroads,Originated Carloads,Originated Tons (millions),Retirement Beneficiaries,Terminated Carloads,Terminated Tons (millions),Total Rail Miles
0,1,Texas,956.0,146200.0,14664.0,54.0,2161300.0,110.9,33300.0,2875900.0,181.9,10370.0
1,2,Illinois,808.0,134500.0,9902.0,47.0,4002900.0,118.9,29600.0,3839700.0,101.4,6768.0
2,3,Florida,759.0,150300.0,3577.0,16.0,639400.0,39.5,28700.0,990400.0,57.2,2716.0
3,4,Pennsylvania,745.0,120830.0,4528.0,59.0,960200.0,50,28600.0,1074900.0,49.5,5228.0
4,5,California,610.0,136840.0,6936.0,27.0,3414100.0,63.8,23900.0,3684400.0,100.8,4948.0
5,6,New York,543.0,127510.0,2389.0,38.0,192600.0,9.7,20300.0,295100.0,15.7,3442.0
6,7,Ohio,537.0,128510.0,5036.0,43.0,1081600.0,52.8,21000.0,1069200.0,60.9,5139.0
7,8,Missouri,487.0,133750.0,5740.0,17.0,451000.0,22,17700.0,654000.0,50.0,3734.0
8,9,Nebraska,453.0,138960.0,8436.0,10.0,377800.0,34.5,14500.0,216600.0,19.4,3138.0
9,10,Georgia,451.0,143050.0,5428.0,29.0,1138900.0,38.4,16400.0,1308400.0,54.1,4538.0
10,11,Virginia,395.0,141490.0,2738.0,10.0,538900.0,26.9,15000.0,871600.0,56.1,3050.0
11,12,Indiana,390.0,132790.0,4798.0,43.0,632400.0,50.2,14300.0,594800.0,53.2,3946.0
12,13,Kansas,356.0,134030.0,4296.0,14.0,458600.0,28.6,12500.0,368500.0,18.2,4748.0
13,14,Kentucky,339.0,128850.0,2457.0,15.0,366400.0,22.6,13200.0,269400.0,19.4,2673.0
14,15,Minnesota,331.0,132590.0,3750.0,19.0,1186900.0,99.1,12600.0,954300.0,75.1,4373.0
15,16,Tennessee,309.0,133000.0,2816.0,27.0,531300.0,14.7,11500.0,636000.0,25.0,2730.0
16,17,Michigan,306.0,125080.0,2352.0,28.0,525700.0,20.9,11500.0,502800.0,28.7,3429.0
17,18,Washington,268.0,138420.0,3619.0,29.0,792100.0,20.2,9700.0,1215800.0,68.2,2867.0
18,19,Arizona,257.0,143050.0,2389.0,10.0,133900.0,4.3,9600.0,301000.0,19.5,1724.0
19,20,Arkansas,257.0,123690.0,2276.0,24.0,296800.0,16.4,9400.0,319400.0,22.4,2554.0
20,21,New Jersey,246.0,119780.0,887.0,19.0,714800.0,15.7,8500.0,766200.0,22.6,1087.0
21,22,North Carolina,241.0,132430.0,1614.0,22.0,295600.0,12.7,9700.0,546500.0,37.5,3125.0
22,23,Alabama,240.0,131300.0,2561.0,25.0,416400.0,32.6,8900.0,430000.0,38.0,3165.0
23,24,Colorado,233.0,137320.0,1814.0,14.0,264100.0,15.2,8300.0,397600.0,27.0,2545.0
24,25,Wisconsin,233.0,135890.0,2732.0,9.0,252900.0,22.9,8900.0,416600.0,39.2,3482.0
25,26,Iowa,232.0,134580.0,2658.0,17.0,517100.0,48.3,8500.0,257300.0,24.5,3827.0
26,27,Maryland,214.0,128920.0,737.0,9.0,77800.0,3.9,8100.0,342900.0,29.8,722.0
27,28,West Virginia,190.0,125870.0,1495.0,11.0,468100.0,52.6,7000.0,77300.0,7.6,2123.0
28,29,Louisiana,189.0,127630.0,2600.0,21.0,444200.0,37.2,6900.0,423300.0,37.0,3001.0
29,30,Oregon,184.0,122140.0,1337.0,22.0,302200.0,11.3,7000.0,423600.0,17.2,2369.0
30,31,South Carolina,183.0,136500.0,1237.0,11.0,355000.0,14,7000.0,527300.0,27.1,2191.0
31,32,Montana,166.0,131230.0,2772.0,7.0,302700.0,32.1,5700.0,44500.0,3.5,3680.0
32,33,Mississippi,137.0,133200.0,1733.0,27.0,121200.0,9,5200.0,144400.0,13.1,2541.0
33,34,Utah,130.0,131520.0,1150.0,8.0,258500.0,15.7,4600.0,241300.0,11.6,1388.0
34,35,Oklahoma,123.0,126220.0,1766.0,18.0,211900.0,19.3,4600.0,186500.0,17.6,3222.0
35,36,Idaho,122.0,126290.0,1176.0,10.0,92700.0,8.7,4300.0,102700.0,9.7,1654.0
36,37,Wyoming,116.0,136770.0,1609.0,6.0,2020000.0,230.4,3600.0,99800.0,10.1,1860.0
37,38,New Mexico,102.0,138850.0,1349.0,6.0,121200.0,6.2,3800.0,107400.0,5.2,1859.0
38,39,Massachusetts,99.0,111830.0,593.0,13.0,130400.0,4.3,3600.0,222700.0,8.3,868.0
39,40,North Dakota,87.0,139470.0,1458.0,7.0,375500.0,35.7,2900.0,127900.0,12.3,3223.0
40,41,Nevada,80.0,141660.0,514.0,2.0,38500.0,2.5,3100.0,79300.0,5.4,1193.0
41,42,Connecticut,77.0,107060.0,111.0,8.0,14400.0,1.4,2600.0,15100.0,1.4,571.0
42,43,Delaware,72.0,119090.0,147.0,6.0,4700.0,0.4,2500.0,40000.0,3.0,230.0
43,44,Maine,50.0,110070.0,466.0,7.0,23400.0,1.8,2100.0,22500.0,1.9,1116.0
44,45,South Dakota,50.0,129640.0,665.0,11.0,167700.0,16.4,1700.0,35400.0,3.4,1868.0
45,46,New Hampshire,23.0,112280.0,169.0,10.0,1430.0,0.1,900.0,7300.0,0.6,369.0
46,47,Rhode Island,16.0,118270.0,28.0,1.0,500.0,<0.05,600.0,6500.0,0.5,143.0
47,48,Vermont,14.0,86750.0,185.0,10.0,6800.0,0.6,600.0,12400.0,1.0,607.0
49,50,Alaska,4.0,105420.0,609.0,1.0,NaN,2.5,200.0,NaN,2.5,506.0
50,51,Hawaii,4.0,NaN,5.0,0.0,0.0,0,200.0,NaN,0.0,0.0

# Merge the two merged datasets (railroad and the remaining)

In [27]:
combined_data = pd.read_excel('Combined_dataset.xlsx')
combined_data['State'].unique()

array(['Alaska', 'California', 'Idaho', 'Maine', 'Michigan', 'Minnesota',
       'Missouri', 'Montana', 'North Carolina', 'New Mexico', 'Oregon',
       'Pennsylvania', 'Tennessee'], dtype=object)

In [28]:
final_data = pd.merge(combined_data, merged_data, on='State', how='left')
final_data

,Unnamed: 0,original_OBJECTID *,original_Site_ID *,original_Site_Name,original_Other_Name,original_Last_Updt,original_Commodity,original_MinReg_ID,original_Remarks,original_Approx_Lon,...,Retirement Payments ($ mil),Freight Rail Average Wages & Benefits Per Employee,Freight Rail Employees,Number of Railroads,Originated Carloads,Originated Tons (millions),Retirement Beneficiaries,Terminated Carloads,Terminated Tons (millions),Total Rail Miles
0,0,1,AK00012,Bornite Project,<Null>,6/6/2018,copper; cobalt,Mr00061,<Null>,-156.944535,...,4.0,105420.0,609.0,1.0,NaN,2.5,200.0,NaN,2.5,506.0
1,1,2,AK00017,Ambler District,<Null>,6/21/2018,cobalt; copper,Mr00061,<Null>,-156.150351,...,4.0,105420.0,609.0,1.0,NaN,2.5,200.0,NaN,2.5,506.0
2,2,3,AK00205,Bohemia Basin,<Null>,4/16/2018,cobalt; nickel; copper,Mr00144,<Null>,-136.428000,...,4.0,105420.0,609.0,1.0,NaN,2.5,200.0,NaN,2.5,506.0
3,3,4,AK00206,Chichagof District,<Null>,4/13/2018,cobalt; nickel; copper,Mr00144,<Null>,-135.199000,...,4.0,105420.0,609.0,1.0,NaN,2.5,200.0,NaN,2.5,506.0
4,4,5,AK00207,Brady Glacier,<Null>,4/16/2018,cobalt; nickel; copper,<Null>,<Null>,-136.932000,...,4.0,105420.0,609.0,1.0,NaN,2.5,200.0,NaN,2.5,506.0
5,5,6,CA00070,Pine Flat,<Null>,4/23/2018,cobalt; nickel,<Null>,<Null>,-123.994000,...,610.0,136840.0,6936.0,27.0,3414100.0,63.8,23900.0,3684400.0,100.8,4948.0
6,6,7,CA00071,Gasquet,Gasquet Laterite; Gasquet Mountain,6/21/2018,cobalt; nickel; chromium,<Null>,<Null>,-123.996000,...,610.0,136840.0,6936.0,27.0,3414100.0,63.8,23900.0,3684400.0,100.8,4948.0
7,7,8,ID00005,Blackbird,<Null>,5/8/2018,cobalt; copper; gold; silver,Mr00145,<Null>,-114.343000,...,122.0,126290.0,1176.0,10.0,92700.0,8.7,4300.0,102700.0,9.7,1654.0
8,8,9,ID00050,Idaho Cobalt Project,Ram; Sunshine; Blackbird,5/8/2018,cobalt; gold; copper,Mr00145,<Null>,-114.362000,...,122.0,126290.0,1176.0,10.0,92700.0,8.7,4300.0,102700.0,9.7,1654.0
9,9,10,ID00051,Iron Creek,<Null>,5/8/2018,copper; cobalt; iron,Mr00145,<Null>,-114.118000,...,122.0,126290.0,1176.0,10.0,92700.0,8.7,4300.0,102700.0,9.7,1654.0
10,10,11,ID00052,Salmon Canyon,Copper Canyon,4/16/2018,copper; cobalt; gold; silver,<Null>,<Null>,-114.558000,...,122.0,126290.0,1176.0,10.0,92700.0,8.7,4300.0,102700.0,9.7,1654.0
11,11,12,ID00054,Blackbird District,<Null>,4/16/2018,copper; cobalt; gold; silver; iron,Mr00145,<Null>,-114.308000,...,122.0,126290.0,1176.0,10.0,92700.0,8.7,4300.0,102700.0,9.7,1654.0
12,12,13,ME00002,Union,Harriman; Crawford Pond,5/11/2018,cobalt; nickel; copper,<Null>,<Null>,-69.241000,...,50.0,110070.0,466.0,7.0,23400.0,1.8,2100.0,22500.0,1.9,1116.0
13,13,14,ME00003,Warren,Area 5,5/11/2018,cobalt; nickel,<Null>,<Null>,-69.256000,...,50.0,110070.0,466.0,7.0,23400.0,1.8,2100.0,22500.0,1.9,1116.0
14,14,15,MI00001,Eagle,<Null>,4/17/2018,nickel; copper; cobalt; gold; silver; platinum...,<Null>,<Null>,-87.889000,...,306.0,125080.0,2352.0,28.0,525700.0,20.9,11500.0,502800.0,28.7,3429.0
15,15,16,MN00002,NorthMet,<Null>,4/16/2018,copper; nickel; platinum; palladium; gold; cob...,<Null>,<Null>,-91.970000,...,331.0,132590.0,3750.0,19.0,1186900.0,99.1,12600.0,954300.0,75.1,4373.0
16,16,17,MN00003,"Birch Lake, Maturi, Spruce Road, Teck�s Mesaba...",Duluth Complex,4/11/2018,copper; nickel; platinum; palladium; gold; sil...,<Null>,<Null>,-91.740000,...,331.0,132590.0,3750.0,19.0,1186900.0,99.1,12600.0,954300.0,75.1,4373.0
17,17,18,MN00008,Tamarack,Tamarack North; Tamarack South,4/16/2018,nickel; copper; cobalt; platinum; palladium; gold,<Null>,<Null>,-93.116000,...,331.0,132590.0,3750.0,19.0,1186900.0,99.1,12600.0,954300.0,75.1,4373.0
18,18,19,MO00001,Fredericktown District,<Null>,5/10/2018,lead; copper; nickel cobalt; iron; silver,Mr00036,<Null>,-90.217000,...,487.0,133750.0,5740.0,17.0,451000.0,22,17700.0,654000.0,50.0,3734.0
19,19,20,MO00002,Higdon,<Null>,6/21/2018,cobalt; nickel; copper; zinc; lead,Mr00036,<Null>,-90.142000,...,487.0,133750.0,5740.0,17.0,451000.0,22,17700.0,654000.0,50.0,3734.0
20,20,21,MO00013,Madison,Fredericktown,5/8/2018,lead; copper; nickel cobalt; iron; silver,Mr00036,<Null>,-90.276000,...,487.0,133750.0,5740.0,17.0,451000.0,22,17700.0,654000.0,50.0,3734.0
21,21,22,MO00014,Boss-Bixby,<Null>,5/10/2018,copper; cobalt; iron,<Null>,<Null>,-91.170000,...,487.0,133750.0,5740.0,17.0,451000.0,22,17700.0,654000.0,50.0,3734.0
22,22,23,MT00002,Black Butte,Sheep Creek,4/23/2018,cobalt; copper; gold; silver,Mr00148,<Null>,-110.894000,...,166.0,131230.0,2772.0,7.0,302700.0,32.1,5700.0,44500.0,3.5,3680.0
23,23,24,MT00029,Smith River District,<Null>,4/19/2018,cobalt; copper; gold; silver,Mr00148,<Null>,-111.149000,...,166.0,131230.0,2772.0,7.0,302700.0,32.1,5700.0,44500.0,3.5,3680.0
24,24,25,NC00001,Webster District,<Null>,5/11/2018,nickel; cobalt,Mr00047,<Null>,-83.213000,...,241.0,132430.0,1614.0,22.0,295600.0,12.7,9700.0,546500.0,37.5,3125.0
25,25,26,NM00041,Black Hawk,<Null>,5/11/2018,cobalt; nickel; zinc; silver; copper; gold; ur...,Mr00154,<Null>,-108.501000,...,102.0,138850.0,1349.0,6.0,121200.0,6.2,3800.0,107400.0,5.2,1859.0
26,26,27,NM00042,Black Hawk District,<Null>,5/18/2018,cobalt; nickel; zinc; silver; copper; gold; ur...,Mr00154,<Null>,-108.501000,...,102.0,138850.0,1349.0,6.0,121200.0,6.2,3800.0,107400.0,5.2,1859.0
27,27,28,OR00001,Turner,Turner-Albright; Mammoth,4/18/2018,gold; copper; silver; zinc; cobalt,<Null>,<Null>,-123.758000,...,184.0,122140.0,1337.0,22.0,302200.0,11.3,7000.0,423600.0,17.2,2369.0
28,28,29,OR00002,Eight Dollar Mountain,<Null>,5/10/2018,nickel; cobalt; chromium,Mr00155,<Null>,-123.663000,...,184.0,122140.0,1337.0,22.0,302200.0,11.3,7000.0,423600.0,17.2,2369.0
29,29,30,OR00005,Nickel Mountain,Riddle; Hanna,4/26/2018,cobalt; nickel,<Null>,<Null>,-123.437000,...,184.0,122140.0,1337.0,22.0,302200.0,11.3,7000.0,423600.0,17.2,2369.0
30,30,31,PA00001,Cornwall,<Null>,4/19/2018,iron; copper; sulfur; cobalt; gold; silver,<Null>,<Null>,-76.411000,...,745.0,120830.0,4528.0,59.0,960200.0,50,28600.0,1074900.0,49.5,5228.0
31,31,37,TN00001,Ducktown District,Ducktown Basin,5/11/2018,copper; cobalt; iron; zinc; lead; silver; gold,Mr00037,Some mineralization extends into Fannin County...,-84.383000,...,309.0,133000.0,2816.0,27.0,531300.0,14.7,11500.0,636000.0,25.0,2730.0

In [29]:
final_data.to_csv('final_merged_data.csv', index = False)  # Export merged pandas DataFrame